/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartment_management;

import static apartment_management.bill.Name;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class profit extends javax.swing.JFrame {

    Statement st;
    Connection conn = null;
    java.sql.PreparedStatement PST = null;
    ResultSet RS = null;

    /**
     * Creates new form profit
     */
    public profit() {
        initComponents();
         this.setDefaultCloseOperation(profit.DISPOSE_ON_CLOSE);
        jLabel3.setVisible(false);
        jLabel7.setVisible(false);
        jLabel1.setVisible(false);
        jLabel8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jButton1 = new javax.swing.JButton();
        printb = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 74, 117));
        jPanel1.setLayout(null);
        jPanel1.add(jYearChooser2);
        jYearChooser2.setBounds(450, 20, 58, 33);
        jPanel1.add(jMonthChooser1);
        jMonthChooser1.setBounds(450, 70, 120, 33);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("profit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 120, 80, 30);

        printb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartment_management/img/ic_print1234.png"))); // NOI18N
        printb.setText("Print");
        printb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbActionPerformed(evt);
            }
        });
        jPanel1.add(printb);
        printb.setBounds(440, 600, 100, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Details");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 160, 148, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Parking Income");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 260, 148, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cost");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(320, 160, 90, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 510, 60, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Profit");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 540, 70, 25);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setBorder(null);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(270, 550, 120, 15);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setBorder(null);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(220, 260, 90, 15);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setBorder(null);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(220, 520, 90, 15);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setBorder(null);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(320, 520, 70, 15);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(220, 220, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(" Income");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(220, 160, 90, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Maintance Income");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 220, 148, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Employee salary");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 370, 148, 25);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField6.setBorder(null);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(320, 370, 70, 15);

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\sumanan\\level5\\project\\Apartment_management\\img\\prof.png")); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 0, 410, 590);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 30, 410, 600);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(450, 170, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = 0;
        x = jMonthChooser1.getMonth() + 1;

        int y = 0;
        y = jYearChooser2.getYear();
//        JOptionPane.showMessageDialog(null,x);
//        JOptionPane.showMessageDialog(null,y);
        int incom = 0;
        int out = 0;
        int profit = 0;
        int month = 0;
        int year = 0;
        try {
            conn = dbconnection.getConnetion();
            String query1 = ("select  year(date),month(date) from bill where year(date)=" + y + " and month(date)=" + x + "");
            java.sql.Statement st = conn.createStatement();
            ResultSet RS = st.executeQuery(query1);
            while (RS.next()) {
                month = RS.getInt("month(date)");
                year = RS.getInt("year(date)");
            }
            if (month == x && year == y) 
            {
                jLabel3.setVisible(true);
                jLabel7.setVisible(true);
                jLabel1.setVisible(true);
                jLabel8.setVisible(true);
                
                
            } else {
                
                jLabel3.setVisible(false);
                jLabel7.setVisible(false);
                jLabel1.setVisible(false);
                jLabel8.setVisible(false);
                 jTextField3.setText("");
                 jTextField6.setText("");
                 jTextField1.setText("");
                 jTextField2.setText("");
                 jTextField4.setText("");
                 jTextField5.setText("");
                 JOptionPane.showMessageDialog(null, "no data");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

       if (month == x && year == y) 
       {
        try {
            conn = dbconnection.getConnetion();
            String query1 = ("select sum(salary) from employee_salary where year(date)=" + y + " and month(date)=" + x + " ");
            java.sql.Statement st = conn.createStatement();
            ResultSet RS = st.executeQuery(query1);
            while (RS.next()) {
                jTextField3.setText(RS.getString("sum(salary)"));
                jTextField6.setText(RS.getString("sum(salary)"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
       }
       else
       {
//           JOptionPane.showMessageDialog(null, "no data");
       }
          if (month == x && year == y) 
          {
        try {
            conn = dbconnection.getConnetion();
            String query1 = ("select sum(amount) from bill where details=\"maintance\" and year(date)=" + y + " and month(date)=" + x + " ;");
            java.sql.Statement st = conn.createStatement();
            ResultSet RS = st.executeQuery(query1);
            while (RS.next()) {
                jTextField1.setText(RS.getString("sum(amount)"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
          }
          
          
           if (month == x && year == y) 
           {
        try {
            conn = dbconnection.getConnetion();
            String query1 = ("select sum(amount) from bill where details=\"parking\" and year(date)=" + y + " and month(date)=" + x + " ;");
            java.sql.Statement st = conn.createStatement();
            ResultSet RS = st.executeQuery(query1);
            while (RS.next()) {
                jTextField2.setText(RS.getString("sum(amount)"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
           }
           
            if (month == x && year == y) 
            {
           
        try {
            conn = dbconnection.getConnetion();
            String query1 = ("select sum(amount) from bill where details=\"maintance\" and year(date)=" + y + " and month(date)=" + x + " or details=\"parking\" and year(date)=" + y + " and month(date)=" + x + " ;");
            java.sql.Statement st = conn.createStatement();
            ResultSet RS = st.executeQuery(query1);
            while (RS.next()) {
                jTextField4.setText(RS.getString("sum(amount)"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        incom = Integer.parseInt(jTextField4.getText());
        out = Integer.parseInt(jTextField3.getText());
        profit = incom - out;
        String profit2 = String.valueOf(profit);
        jTextField5.setText(profit2);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void printbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbActionPerformed
        printRecord(jPanel2);
    }//GEN-LAST:event_printbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    private javax.swing.JButton printb;
    // End of variables declaration//GEN-END:variables

    private void printRecord(JPanel panel) {
        // Create PrinterJob Here
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("Print Record");
        // Set Printable
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                // Check If No Printable Content
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                // Make 2D Graphics to map content
                Graphics2D graphics2D = (Graphics2D) graphics;
                // Set Graphics Translations
                // A Little Correction here Multiplication was not working so I replaced with addition
                graphics2D.translate(pageFormat.getImageableX() + 10, pageFormat.getImageableY() + 10);
                // This is a page scale. Default should be 0.3 I am using 0.5
                graphics2D.scale(1.2, 1);

                // Now paint panel as graphics2D
                panel.paint(graphics2D);

                // return if page exists
                return Printable.PAGE_EXISTS;
            }
        });
        // Store printerDialog as boolean
        boolean returningResult = printerJob.printDialog();
        // check if dilog is showing
        if (returningResult) {
            // Use try catch exeption for failure
            try {
                // Now call print method inside printerJob to print
                printerJob.print();
            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }
}
