/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartment_management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class salary1 extends javax.swing.JFrame {

    Statement st;
    Connection conn = null;
    java.sql.PreparedStatement PST = null;
    ResultSet RS = null;

    /**
     * Creates new form salary
     */
    public salary1() {
        initComponents();
        this.setDefaultCloseOperation(salary1.DISPOSE_ON_CLOSE);
        showdwp();
        sc1.setVisible(false);
        l1.setVisible(false);
        userid.setVisible(false);
        name2.setVisible(false);
        salary.setVisible(false);
    }

    public ArrayList<payment> userlist() {
        ArrayList<payment> userlist = new ArrayList<>();
        try {
            conn = dbconnection.getConnetion();
            String query1 = ("SELECT * from employee_salary ");
            java.sql.Statement st = conn.createStatement();
            ResultSet RS = st.executeQuery(query1);
            payment payment;
            while (RS.next()) {
                payment = new payment(RS.getString("userid"), RS.getString("Date"), RS.getString("salary"));
                userlist.add(payment);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return userlist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        m1 = new javax.swing.JCheckBox();
        m2 = new javax.swing.JCheckBox();
        m3 = new javax.swing.JCheckBox();
        m4 = new javax.swing.JCheckBox();
        m5 = new javax.swing.JCheckBox();
        m6 = new javax.swing.JCheckBox();
        m7 = new javax.swing.JCheckBox();
        m8 = new javax.swing.JCheckBox();
        m9 = new javax.swing.JCheckBox();
        m10 = new javax.swing.JCheckBox();
        m11 = new javax.swing.JCheckBox();
        m12 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        userid = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        sc1 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 74, 117));

        jPanel2.setBackground(new java.awt.Color(5, 74, 117));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Months", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        m1.setBackground(new java.awt.Color(5, 74, 117));
        m1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setText("1");

        m2.setBackground(new java.awt.Color(5, 74, 117));
        m2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setText("2");

        m3.setBackground(new java.awt.Color(5, 74, 117));
        m3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setText("3");

        m4.setBackground(new java.awt.Color(5, 74, 117));
        m4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m4.setForeground(new java.awt.Color(255, 255, 255));
        m4.setText("4");

        m5.setBackground(new java.awt.Color(5, 74, 117));
        m5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m5.setForeground(new java.awt.Color(255, 255, 255));
        m5.setText("5");

        m6.setBackground(new java.awt.Color(5, 74, 117));
        m6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m6.setForeground(new java.awt.Color(255, 255, 255));
        m6.setText("6");

        m7.setBackground(new java.awt.Color(5, 74, 117));
        m7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m7.setForeground(new java.awt.Color(255, 255, 255));
        m7.setText("7");

        m8.setBackground(new java.awt.Color(5, 74, 117));
        m8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m8.setForeground(new java.awt.Color(255, 255, 255));
        m8.setText("8");

        m9.setBackground(new java.awt.Color(5, 74, 117));
        m9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m9.setForeground(new java.awt.Color(255, 255, 255));
        m9.setText("9");

        m10.setBackground(new java.awt.Color(5, 74, 117));
        m10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m10.setForeground(new java.awt.Color(255, 255, 255));
        m10.setText("10");

        m11.setBackground(new java.awt.Color(5, 74, 117));
        m11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m11.setForeground(new java.awt.Color(255, 255, 255));
        m11.setText("11");

        m12.setBackground(new java.awt.Color(5, 74, 117));
        m12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m12.setForeground(new java.awt.Color(255, 255, 255));
        m12.setText("12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m1)
                    .addComponent(m2)
                    .addComponent(m3)
                    .addComponent(m4))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m5)
                    .addComponent(m6)
                    .addComponent(m7)
                    .addComponent(m8))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m12)
                    .addComponent(m11)
                    .addComponent(m10)
                    .addComponent(m9))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m1)
                    .addComponent(m5)
                    .addComponent(m9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m2)
                    .addComponent(m6)
                    .addComponent(m10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m3)
                    .addComponent(m7)
                    .addComponent(m11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m4)
                    .addComponent(m8)
                    .addComponent(m12))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(5, 74, 117));
        jPanel3.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(5, 74, 117));
        jPanel6.setLayout(null);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("    ID");
        jTextField3.setBorder(null);
        jTextField3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField3MouseMoved(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField3MouseReleased(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel6.add(jTextField3);
        jTextField3.setBounds(0, 0, 290, 40);

        userid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userid.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        userid.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                useridMouseMoved(evt);
            }
        });
        userid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                useridFocusGained(evt);
            }
        });
        userid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                useridMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                useridMouseReleased(evt);
            }
        });
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                useridKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                useridKeyTyped(evt);
            }
        });
        jPanel6.add(userid);
        userid.setBounds(0, 0, 290, 40);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 0, 310, 40);

        jPanel7.setBackground(new java.awt.Color(5, 74, 117));
        jPanel7.setLayout(null);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jTextField4.setText("     Salary");
        jTextField4.setBorder(null);
        jTextField4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField4MouseMoved(evt);
            }
        });
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField4MouseReleased(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel7.add(jTextField4);
        jTextField4.setBounds(0, 0, 290, 40);

        salary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salary.setBorder(javax.swing.BorderFactory.createTitledBorder("Salary"));
        salary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                salaryMouseMoved(evt);
            }
        });
        salary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salaryFocusGained(evt);
            }
        });
        salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salaryMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salaryMouseReleased(evt);
            }
        });
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryKeyTyped(evt);
            }
        });
        jPanel7.add(salary);
        salary.setBounds(0, 0, 290, 40);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(0, 150, 310, 40);

        jPanel8.setBackground(new java.awt.Color(5, 74, 117));
        jPanel8.setLayout(null);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setText("     Name");
        jTextField5.setBorder(null);
        jTextField5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField5MouseMoved(evt);
            }
        });
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField5MouseReleased(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel8.add(jTextField5);
        jTextField5.setBounds(0, 0, 290, 40);

        name2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name2.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        name2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                name2MouseMoved(evt);
            }
        });
        name2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name2FocusGained(evt);
            }
        });
        name2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                name2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                name2MouseReleased(evt);
            }
        });
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });
        name2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name2KeyTyped(evt);
            }
        });
        jPanel8.add(name2);
        name2.setBounds(0, 0, 290, 40);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(0, 70, 310, 40);

        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        sc1.setViewportView(l1);

        jPanel3.add(sc1);
        sc1.setBounds(0, 40, 290, 80);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartment_management/img/save1234.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apartment_management/img/Previous1234.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Print month profit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Payment", jPanel1);

        jPanel4.setBackground(new java.awt.Color(5, 74, 117));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Date", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Show details", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseMoved

    }//GEN-LAST:event_jTextField3MouseMoved

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained

    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        userid.setText("");
        jTextField3.setBorder(new LineBorder(Color.white, 1));
        jTextField3.setVisible(false);
        userid.setVisible(true);
        userid.requestFocus();
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseReleased

    }//GEN-LAST:event_jTextField3MouseReleased

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void useridMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useridMouseMoved

    }//GEN-LAST:event_useridMouseMoved

    private void useridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_useridFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_useridFocusGained

    private void useridMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useridMouseExited
        if (userid.getText().equals("")) {
            jTextField3.setVisible(true);
            userid.setVisible(false);
        } else {
            jTextField3.setVisible(false);
            userid.setVisible(true);
        }
    }//GEN-LAST:event_useridMouseExited

    private void useridMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useridMouseReleased

    }//GEN-LAST:event_useridMouseReleased

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void useridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyTyped
        if (userid.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_useridKeyTyped

    private void jTextField4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4MouseMoved

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setVisible(false);
        salary.setVisible(true);
        salary.requestFocus();
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4MouseReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void salaryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryMouseMoved

    private void salaryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryFocusGained

    private void salaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryMouseExited

    private void salaryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryMouseReleased

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void salaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryKeyTyped

    private void jTextField5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseMoved

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setVisible(false);
        name2.setVisible(true);
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseReleased

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyTyped

    private void name2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_name2MouseMoved

    private void name2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_name2FocusGained

    private void name2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_name2MouseExited

    private void name2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_name2MouseReleased

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

    private void name2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_name2KeyTyped

    private void useridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyReleased
        if (userid.getText().equals("")) {
            l1.setVisible(false);
            sc1.setVisible(false);
            jPanel8.setVisible(true);
            m1.setSelected(false);
            m2.setSelected(false);
            m3.setSelected(false);
            m4.setSelected(false);
            m5.setSelected(false);
            m6.setSelected(false);
            m7.setSelected(false);
            m8.setSelected(false);
            m9.setSelected(false);
            m10.setSelected(false);
            m11.setSelected(false);
            m12.setSelected(false);
        } else {
            l1.setVisible(true);
            sc1.setVisible(true);
            DefaultListModel model = new DefaultListModel();
            model.clear();
            l1.setModel(model);
            jPanel8.setVisible(false);
            comloadowner();
        }
    }//GEN-LAST:event_useridKeyReleased

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        m1.setSelected(false);
        m2.setSelected(false);
        m3.setSelected(false);
        m4.setSelected(false);
        m5.setSelected(false);
        m6.setSelected(false);
        m7.setSelected(false);
        m8.setSelected(false);
        m9.setSelected(false);
        m10.setSelected(false);
        m11.setSelected(false);
        m12.setSelected(false);

        jTextField5.setVisible(false);
        name2.setVisible(true);
        userid.setText(l1.getSelectedValue());
        try {
            conn = dbconnection.getConnetion();
            PST = conn.prepareStatement("SELECT * FROM employee Where userid=?");
            PST.setString(1, l1.getSelectedValue());
            RS = PST.executeQuery();
            if (RS.next());
            {
                name2.setText(RS.getString("username"));
            }
        } catch (SQLException ex) {
            //  Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);

        }
        jPanel8.setVisible(true);
        sc1.setVisible(false);
        l1.setVisible(false);
        int mon = 0;
        try {
            conn = dbconnection.getConnetion();
            PST = conn.prepareStatement("select month(Date) from employee_salary where userid=? order by month(date) desc;");
            PST.setString(1, l1.getSelectedValue());
            RS = PST.executeQuery();
            if (RS.next());
            {
                int month = RS.getInt("month(Date)");
                mon = month;
            }
            if (mon == 1) {
                m1.setSelected(true);
            } else if (mon == 2) {
                m1.setSelected(true);
                m2.setSelected(true);
            } else if (mon == 3) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
            } else if (mon == 4) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
            } else if (mon == 5) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
                m5.setSelected(true);
            } else if (mon == 6) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
                m5.setSelected(true);
                m6.setSelected(true);
            } else if (mon == 7) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
                m5.setSelected(true);
                m6.setSelected(true);
                m7.setSelected(true);
            } else if (mon == 8) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
                m5.setSelected(true);
                m6.setSelected(true);
                m7.setSelected(true);
                m8.setSelected(true);
            } else if (mon == 9) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
                m5.setSelected(true);
                m6.setSelected(true);
                m7.setSelected(true);
                m8.setSelected(true);
                m9.setSelected(true);
            } else if (mon == 10) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
                m5.setSelected(true);
                m6.setSelected(true);
                m7.setSelected(true);
                m8.setSelected(true);
                m9.setSelected(true);
                m10.setSelected(true);
            } else if (mon == 11) {
                m1.setSelected(true);
                m2.setSelected(true);
                m3.setSelected(true);
                m4.setSelected(true);
                m5.setSelected(true);
                m6.setSelected(true);
                m7.setSelected(true);
                m8.setSelected(true);
                m9.setSelected(true);
                m10.setSelected(true);
                m11.setSelected(true);
            } else {

            }

        } catch (SQLException ex) {
            //  Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_l1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String query = "INSERT INTO employee_salary(userid,date,salary)values(?,?,?)";
            conn = dbconnection.getConnetion();
            PST = conn.prepareStatement(query);
            PST.setString(1, userid.getText());
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date(System.currentTimeMillis());
            String day = (formatter.format(date));
            PST.setString(2, day);
            PST.setString(3, salary.getText());
            PST.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insert Successfully");
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(null, "Duplicated Entry");
        }
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
//       new menu().setVisible(true);
        menu m = new menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new profit().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JList<String> l1;
    private javax.swing.JCheckBox m1;
    private javax.swing.JCheckBox m10;
    private javax.swing.JCheckBox m11;
    private javax.swing.JCheckBox m12;
    private javax.swing.JCheckBox m2;
    private javax.swing.JCheckBox m3;
    private javax.swing.JCheckBox m4;
    private javax.swing.JCheckBox m5;
    private javax.swing.JCheckBox m6;
    private javax.swing.JCheckBox m7;
    private javax.swing.JCheckBox m8;
    private javax.swing.JCheckBox m9;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField salary;
    private javax.swing.JScrollPane sc1;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables

    private void comloadowner() {
        DefaultListModel Model = new DefaultListModel();
        l1.setModel(Model);
        try {
            conn = dbconnection.getConnetion();
            PST = conn.prepareStatement("select distinct userid from employee where userid like '" + userid.getText() + "%' ");
            RS = PST.executeQuery();
            while (RS.next()) {
                String did = RS.getString("userid");
                Model.addElement(did);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }

    private void showdwp() {
        ArrayList<payment> list = userlist();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[3];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getempid();
            row[1] = list.get(i).getdate();
            row[2] = list.get(i).getsalary();

            model.addRow(row);
        }
    }
}
